### ISSUE TITLE
Meaningful / consistent exception system

### ISSUE THREAD

**Issue by bjoern-arnold** [eclipse-tractusx/SSI-agent-lib#30]
# Summary
Exception classes defined within the library do not have a clear purpose and hierarchy, they are declared unnecessarily and used inconsistently. Thus, the exception system should be re-structured such that clients of the library can identify the cause of an error and handle it properly.

# Details & Examples

## Unnecessary “throws” declarations

- All methods of class _OctetKeyPairFactory_ declare `throws java.io.IOException`, however the code cannot throw an exception of that type.

## Inconsistent exception hierarchy: 
- There is a “base” exception class _SsiException_, however the only child class is _DidParseException_.
- _JwtException_ is supposed to be the base class for exceptions related to JWT, however there are other exception related to JWT that do not extend this class, e.g., _JwtSignatureVerificationKeyNotFoundException_.
- _UnsupportedDidMethodException_ and _UnsupportedVerificationMethodException_ are unchecked exceptions, while _UnsupportedSignatureTypeException_ is a checked exception.
Inconsistent use of exceptions:
- Method _DidWebParser.parse_ throws a _DidParseException_ instead of the more specific _UnsupportedDidMethodException_.
- Method _JsonLdValidatorImpl.validateJsonLd_ may throw a _RuntimeException_ (in method _findUndefinedTerms_) that is not wrapped in an _InvalidJsonLdException_.

## Miscellaneous
- Classes _InvalidePrivateKeyFormat_ and _InvalidePublicKeyFormat_ are misspelled, as well as the messages.
- Classes _InvalidePrivateKeyFormat_, _InvalidePublicKeyFormat_, _JwtSignatureVerificationKeyNotFoundException_ and _KeyGenerationException_ have a constructor that accepts a _Throwable_ which is neither propagated to the super method nor stored within the class.

# Suggestions
- Define one "base" exception class as a checked exception.
- Let all other exception classes extend the base exception class.
- If necessary, structure the exceptions further, e.g. let all exception classes related to JWT extend _JwtException_. Consider doing the same for exceptions related to DID, Keys, JSON-LD.
- Make sure that the library only throws standard (JDK) exceptions and exceptions defined by the library itself.
- All constructors must call the respective parent constructor.
- Specify a _serialVersionUID_ for all exception classes.
- Review error messages for correctness, level of detail and consistency.
- Remove unnecessary throws declarations.

**Comment by koptan** [comment]
@koptan, assigned to me
