### ISSUE TITLE
Signature `ProofOptions` not included

### ISSUE THREAD

**Issue by matgnt** [eclipse-tractusx/SSI-agent-lib#34]
Since I'm running a couple of tests with the MIW and it's VCs, I ran into the following:

I fetch a VC from MIW.
I create a VP with this VC (with MIW)
I verify the VP (and its VCs) with the MIW and it is valid.

I change the VC `proof.created`
I create a VP with this changed VC (with MIW)
I verify the VP (and its VCs) with the MIW and it is valid.

I think the last step should NOT be a valid result!

It looks to me like for creating the signature, only the 'unsecuredDocument' is taken, but not the 'proofOptions'.

Can you please double check this desired behavior? To my understanding it should be the hash from the 'proofOptions' +  the hash from the 'unsecuredDocument' that are concatenated and then used as the data that is signed.

Can we add a test case that verifies the produced VC/VPs with a 3rd party library? Just to make sure compatibility is ok.

--
Matthias Binzer

**Comment by matgnt** [comment]
I've added a test case for ProofOptions manipulation that fails without any additional changes - because it should fail.

I can change the 'created' or 'proofPuspose' without the signature check ('verify') failing.

The specs for JsonLd Proofs (now Data Integrity Proofs) have changed quite heavily in recent times, but I think a good example can be found here:
https://www.w3.org/TR/vc-di-eddsa/#test-vectors

and the more formal description here:
https://www.w3.org/TR/vc-di-eddsa/#hashing-ed25519signature2020

**Comment by koptan** [comment]
@borisrizov-zf, please assign this to me.
