### ISSUE TITLE
DID Method Identifier not parsed correctly

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-tractusx/SSI-agent-lib#49]
**When** I parse the following DID using the `DidParser`:
- `did:web:localhost%3A8080:c4d74327-55d3-485d-a54b-b6aee528f968`

**Then** I get the following method identifier:
- `localhost%3A8080:c4d74327-55d3-485d-a54b-b6aee528f968`

I would **expect** to get this method identifier:
- `c4d74327-55d3-485d-a54b-b6aee528f968`

**Comment by borisrizov-zf** [comment]
This is the expected behavior according to the ABNF for a did.
[Link to did syntax spec](https://www.w3.org/TR/did-core/#did-syntax)

Breakdown
```
localhost%3A8080:c4d74327-55d3-485d-a54b-b6aee528f968
matches
*( *idchar ":" ) 1*idchar
```

I'm closing this as it is not relevant.
