### ISSUE TITLE
credentialStatus id not getting added if credentials is created using VerifiableCredentialBuilder

### ISSUE THREAD

**Issue by nitin-vavdiya** [eclipse-tractusx/SSI-agent-lib#70]
If we build credentials using `VerifiableCredentialBuilder` then  `credentialStatus` is not available in `VerifiableCredential`

Ie:

```
VerifiableCredentialStatusList2021Entry statusList2021Entry = new VerifiableCredentialStatusList2021Entry(Map.of(
        "id", "https://example.com/credentials/status/3#1",
        "type", "BitstringStatusListEntry",
        "statusPurpose", "revocation",
        "statusListIndex", "",
        "statusListCredential", "https://example.com/credentials/status/3"
));

VerifiableCredential vc = new VerifiableCredentialBuilder()
  .context(contexts)
  .id(URI.create(issuerDoc.getId() + "#" + id))
  .type(verifiableCredentialType)
  .issuer(issuerDoc.getId())
  .expirationDate(expiryDate.toInstant())
  .issuanceDate(Instant.now())
  .verifiableCredentialStatus(statusList2021Entry)
  .credentialSubject(verifiableCredentialSubject)
  .build();


```

Now if you create a JSON string using `vc.toJson()` then it creates JSON string without `credentialStatus`

**Comment by borisrizov-zf** [comment]
Wasn't this intentionally removed by @koptan due to the fact that the revocation is not implemented?

**Comment by koptan** [comment]
> Wasn't this intentionally removed by @koptan due to the fact that the revocation is not implemented?

Yes, this is correct, I removed because the revocation is using new context URL from VC V2 data model, and that time we decide to postponed for some time later.
